name: Run salt tests
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: plus3it/actions-workflows/.github/workflows/test-salt-linux.yml@84885d2116bdcaab046d6bf927127bb58cb74ae8
    strategy:
      matrix:
        os_version:
          - 7
          - 8
        salt_state:
          - forescout-secure-connector
        salt_pillar_root:
          - ./tests/pillar/test-forescout-secure-connector
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}
